"""empty message

Revision ID: f0ab33d4e1ae
Revises: a4f6dff4b72f
Create Date: 2020-10-13 01:28:26.891899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0ab33d4e1ae'
down_revision = 'a4f6dff4b72f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Candidate')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Candidate',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Candidate_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name='Candidate_company_id_fkey'),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], name='Candidate_job_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='Candidate_pkey')
    )
    op.drop_table('candidate')
    # ### end Alembic commands ###
